- name: Copy file
  hosts: all
  tasks:
    - name: Copy the file
      ansible.builtin.copy:
       src: /home/centos/ansible-test/roles/Copy/files/inv
       dest: /home/centos/
       remote_src: yes
